### ISSUE TITLE
Could not find loader 'python3'

### ISSUE THREAD

**Issue by klaszlo** [LeoIannacone/totem-plugin-volumewheel#1]
Hi,

I'm on ubuntu 14.10, with totem version 3.10.1-1ubuntu6.

Whenever I try to load volumewheel plugin it fails with:
(totem:6721): libpeas-WARNING **: Could not find loader 'python3' for plugin 'volumewheel'

my package list:
gir1.2-totem-1.0          3.10.1-1ubuntu6
gir1.2-totem-plparser-1.0 3.10.2-3ubuntu1
libtotem-plparser17       3.4.5-1  
libtotem-plparser18       3.10.2-3ubuntu1
libtotem0                 3.10.1-1ubuntu6
totem                     3.10.1-1ubuntu6
totem-common              3.10.1-1ubuntu6
totem-mozilla             3.10.1-1ubuntu6
totem-plugins             3.10.1-1ubuntu6
totem-plugins-extra       3.10.1-1ubuntu6

Full console output:
las@lasasasa:~/.local/share/totem/plugins$ totem
(totem:7229): GStreamer-CRITICAL **: gst_mini_object_copy: assertion 'mini_object != NULL' failed

(totem:7229): GStreamer-CRITICAL **: gst_caps_get_size: assertion 'GST_IS_CAPS (caps)' failed

(totem:7229): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed

*\* (totem:7229): CRITICAL **: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed

(totem:7229): Grilo-WARNING *_: [registry] grl-registry.c:472: Could not open plugins' info directory '/usr/lib/x86_64-linux-gnu/grilo-0.2': Error opening directory '/usr/lib/x86_64-linux-gnu/grilo-0.2': No such file or directory
(totem:7229): Totem-WARNING *_: Failed to load grilo plugins: All configured plugin paths are invalid
sys:1: Warning: /build/buildd/glib2.0-2.42.1/./glib/giounix.c:410Error while getting flags for FD: Bad file descriptor (9)
(totem:7229): libpeas-WARNING **: Could not find loader 'python3' for plugin 'volumewheel'
^C

**Comment by LeoIannacone** [comment]
As written in the README file, this plugin is compatible only with Totem >= 3.12.

Sorry for this, you have wait for Ubuntu Vivid 15.04 which should ship Totem 3.14 (hopefully).
